[package]
authors = ["Princess Lana <ianagbip1oti@gmail.com>"]
name = "princhess"
version = "0.0.0-dev"
edition = "2021"

[[bin]]
name = "princhess"
path = "src/main.rs"

[dependencies]
arc-swap = "=1.6.0"
arrayvec = "=0.7.4"
argparse = "=0.2.2"
dashmap = "=5.5.3"
fastapprox = "=0.3.1"
nohash-hasher = "=0.2.0"
log = "=0.4.20"
memmap = "=0.7.0"
once_cell = "=1.19.0"
pretty_env_logger = "=0.5.0"
shakmaty = "=0.26.0"

[build-dependencies]
bindgen = "=0.69.1"
cc = "=1.0.83"

[profile.release]
lto = true
