[package]
authors = ["Princess Lana <ianagbip1oti@gmail.com>"]
name = "princhess"
version = "0.0.0-dev"
[[bin]]
name = "princhess"
path = "src/main.rs"

[build-dependencies]
slurp = "1.0.1"

[dependencies]
arc-swap = "=1.3.0"
arrayvec = "=0.7.2"
argparse = "=0.2.2"
crossbeam = "=0.3.2"
dashmap = "=5.4.0"
fastapprox = "=0.3.0"
float-ord = "=0.2.0"
nohash-hasher = "=0.2.0"
log = "=0.4.14"
memmap = "=0.7.0"
once_cell = "=1.17.0"
pretty_env_logger = "=0.4.0"
pod = "=0.5.0"
pgn-reader = "=0.19.0"
rand = { version = "=0.7.3", features = ["small_rng"] }
shakmaty = "=0.20.7"
shakmaty-syzygy = "=0.18.0"
slurp = "=1.0.1"
smallvec = "=0.6.14"

[profile.release]
lto = true
