[package]
authors = ["Princess Lana <ianagbip1oti@gmail.com>", "Jacob Jackson <jacobbfjackson@gmail.com>"]
build = "src/build.rs"
name = "princhess"
version = "0.0.0-dev"
[[bin]]
name = "princhess"
path = "src/main.rs"

[build-dependencies]
slurp = "1.0.1"

[dependencies]
arc-swap = "=1.3.0"
argparse = "=0.2.2"
chess = "=3.2.0"
crossbeam = "=0.3.2"
float-ord = "=0.2.0"
log = "=0.4.14"
memmap = "=0.7.0"
once_cell = "=1.8.0"
pretty_env_logger = "=0.4.0"
pod = "=0.5.0"
pgn-reader = "=0.18.0"
rand = "=0.4.6"
shakmaty = "=0.19.0"
shakmaty-syzygy = "=0.16.1"
slurp = "=1.0.1"
smallvec = "=0.6.14"

[profile.release]
lto = true
