[package]
authors = ["Jacob Jackson <jacobbfjackson@gmail.com>"]
name = "mcts"
version = "0.0.0-dev"

[dependencies]
arena = { path = "../arena" }
crossbeam = "0.3"
rand = "0.4"
smallvec = "0.6"
pod = "0.5.0"
