name: Games

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  games:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        games: [bullet, blitz, rapid]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: cp target/release/princhess bin/princhess
      - run: docker-compose -f bin/docker-compose.yml up ${{ matrix.games }}
