name: Games

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  games:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: docker-compose up crash_test
